### ISSUE TITLE
Download Location Button Becomes Unresponsive After First Click

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#20]
The "Change Download Location" button on the download page becomes unresponsive after the first click, and the button needs to be reset by switching to the home page or about page. This issue makes it difficult for users who need to change their download location multiple times, as they have to keep navigating away from the download page to reset the button.

**Comment by SJPBP** [comment]
It ssems like the Download location button becomes inactive because the segmented button is set up to toggle between two segments. When you click on one segment, it becomes active and the other segment becomes inactive. So when you click on the Download location segment, it becomes active and the other segment (About) becomes inactive. Then, when you click on the About segment, it becomes active and the Download location segment becomes inactive again.

**Comment by AlbertSolomon** [comment]
@SJPBP I see, let me go through ``customtkinter`` wiki page. Maybe a solution lies there.
