### ISSUE TITLE
Application Error: TclError When Closing the Application

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#27]
When attempting to close the application, a TclError is thrown, displaying the message "can't invoke 'frame' command: application has been destroyed." This error may occur due to the application not properly deallocating the resources it uses, causing issues with the "frame" command when closing the application. Users may be unable to close the application without encountering the error message. The application should be updated to properly deallocate its resources before closing to prevent the TclError from occurring. This is how the error looks like:

```
Python\Python310\lib\tkinter\__init__.py", line 2601, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "frame" command: application has been destroyed
Error occurred at line: 678
```

**Comment by treecake10** [comment]
On lines 644-646 in setup.py:

page_number = 1
displayUI()
app.mainloop()

Line 645 seems to be unnecessarily called because it is already being called within the try block inside of the main function. My proposition is to comment out 645 and 646, and then call 'app.mainloop()' after 'displayUI()' within the try block inside of main so as to reduce the number of function calls and have resources deallocated at the end.

**Comment by AlbertSolomon** [comment]
Noted, Thanks for the insight 🤝🏾
